image: Visual Studio 2017

tests: off

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 14 x64
  - yarn

branches:
  only:
  - main
build_script:
- sh: >-
    cd client
    
    yarn electron:build
    
