service: pvs
frameworkVersion: '2.47.0'
configValidationMode: error
variablesResolutionMode: 20210326
package:
  individually: true
  patterns:
    - '!./**'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: 'https://cognito-idp.${self:provider.region}.amazonaws.com/${ssm:/info/cognito/user-pool/id}'
        audience:
          - ${ssm:/info/cognito/user-pool/client/id}

plugins:
  - serverless-ssm-publish

functions:
  process-lumosity-emails:
    handler: process-lumosity-emails.saveattachments
    events:
      - s3:
          bucket: ${ssm:/info/lambda/ses/bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${ssm:/info/lambda/ses/prefix}
          existing: true
    environment:
      DEST_BUCKET: ${ssm:/info/lambda/ses/bucket}
      DEST_PREFIX: reports
      S3_ENDPOINT: "https://s3.us-west-2.amazonaws.com"
    role: ${ssm:/role/lambda/ses/process}
    package:
      patterns:
        - 'process-lumosity-emails/package*.json'
        - 'process-lumosity-emails/node_modules/**'
        - 'process-lumosity-emails/*.js'

  write-user-on-verify:
    handler: on-user-verify/verified.handler
    environment:
      USERS_TABLE: ${ssm:/info/dynamo/table/users}
      DYNAMO_ENDPOINT: "https://dynamodb.${self:provider.region}.amazonaws.com"
    role: ${ssm:/role/lambda/dynamodb}
    package:
      patterns:
        - 'on-user-verify/*.js'

  api:
    handler: api/api.getUser
    events:
      - httpApi:
          method: GET
          path: /user
          authorizer: serviceAuthorizer
    environment:
      USERS_TABLE: ${ssm:/info/dynamo/table/users}
      DYNAMO_ENDPOINT: "https://dynamodb.${self:provider.region}.amazonaws.com"
    role: ${ssm:/role/lambda/dynamodb}
    package:
      patterns:
        - 'api/*.js'

resources:
  Resources:
    PostConfirmationTriggerInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: ${ssm:/info/cognito/user-pool/arn}
        FunctionName: ${self:service}-${self:provider.stage}-write-user-on-verify
  Outputs:
    PostConfirmationLambdaArn:
      Value: !GetAtt WriteDashuserDashonDashverifyLambdaFunction.Arn
      Export:
        Name: 'post-confirmation-lambda-arn'
      Description: Arn for the post-cognito-verification lambda trigger

custom:
  ssmPublish:
    enabled: true
    params:
      - path: /info/lambdas/write-user-on-verify/arn
        source: PostConfirmationLambdaArn
        description: Arn for the post-cognito-verification lambda trigger

